### ISSUE TITLE
[Feat] Add support for non-anchor tags to linkTo

### ISSUE THREAD

**Issue by brandonroberts** [angular-component/router#1]
Also update the linkActive directive to included non-anchor tags

**Comment by meeroslav** [comment]
Do we really want to support bad practice? What would be the use case for this?

**Comment by brandonroberts** [comment]
I thought about this also. It is something the Angular Router supports but I don't think we need to add it.

**Comment by meeroslav** [comment]
We can mark it with `wontfix`. 

If someone requests this feature in the future we can always reevaluate this decision, if there are strong arguments for it.
