### ISSUE TITLE
Consider new name

### ISSUE THREAD

**Issue by meeroslav** [angular-component/router#65]
The current name `angular-routing` is too similar to `@angular/router`. This would lead to confusion. Additionally, the name is too generic leading to difficulty when using search engines (searching for `angular routing` would most likely point to numerous articles and docs on `@angular/router`).

Let's try to brainstorm here possible names in the following format.

**Suggested name:** FooBar
**Explanation(if needed)**: Foo is to angular was Bar is to routing

**Comment by meeroslav** [comment]
Let me start with:

**Suggested name**: Routek
**Explanation**: Play on words: Router + Tech

**Suggested name**: Transporter
**Explanation**: Transports application from one route to another

**Suggested name**: Trasa
**Explanation**: `Trasa` stands for Route in multiple Slavic languages (Slovak, Serbian, Czech, Polish, Croatian...)

**Suggested name**: Vessel
**Explanation**: Transporting application from one route to another

**Comment by mhartington** [comment]
`@ngx/rooter` 😬

**Comment by joelhooks** [comment]
`angular-declarative-rout[er|ing]` or something similar is considerably less confusing on all fronts than some randomly plucked or clever word.

I think the current name is fine though 😅

**Comment by brandonroberts** [comment]
@joelhooks I like the current name also, but its overloaded with existing Angular Router concepts like a "Routing Module".

**Comment by meeroslav** [comment]
Any name would stick after a while. I would personally choose something that's easy to pronounce and unique enough for easy googling.

Unfortunately "router" is already taken.

**Comment by Tysiachnyi** [comment]
Suggested name: Road
Explanation: helps to get to the right place

**Comment by LayZeeDK** [comment]
Suggested name: Cowpath
Explanation: Paving the cowpath when the Angular Router doesn't evolve.

**Comment by LayZeeDK** [comment]
Suggested name: Component Router
Explanation: None needed

**Comment by maartentibau** [comment]
Suggested names: AppRouter / NavRouter / RootRouter / Intersection
Explanation: Should explain itself

**Comment by brandonroberts** [comment]
> Suggested name: Component Router
> Explanation: None needed

I do like @angular-component/router

**Comment by meeroslav** [comment]
> Suggested name: Road
> 
> Explanation: helps to get to the right place

I had an idea for skylines/airlines. Could use rocket emoji. 

Thanks for a reminder.

**Comment by lacolaco** [comment]
Station, it welcomes passengers and delivers them to destinations.

**Comment by maartentibau** [comment]
Suggested name: Routable
Explanation: 🗺

**Comment by kievsash** [comment]
angular-template-router
angular-template-driven-router

**Comment by JohannesHoppe** [comment]
**ngx-pathfinder** 🚀
**angular-pathfinder**
(since you don't like the ngx prefix that much)

**Comment by GreatHawkeye** [comment]
> Suggested name: Component Router
> Explanation: None needed

This!
And even better :  `@angular-component/router` as @brandonroberts said. This namespace will allow further component-related library ( `@angular-component/forms` ...)

**Comment by LayZeeDK** [comment]
> This namespace will allow further component-related library ( @angular-component/forms ...)

`@angular-component/store`? 😉

**Comment by fxck** [comment]
is it on npm yet, or I started installing at the wrongest of times? :)

**Comment by meeroslav** [comment]
@fxck Not yet, please use the old algular-routing. We will roll the new name with the next version.

**Comment by fxck** [comment]
when might that be @meeroslav ?

**Comment by brandonroberts** [comment]
@fxck `@angular-component/router` is published to npm as version `0.4.0`

**Comment by meeroslav** [comment]
If you are migrating from `angular-routing` make sure you change the `RoutingModule` to `ComponentRouterModule`.
